# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import notes_pb2 as notes__pb2


class NotesServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateNote = channel.unary_unary(
                '/notes.NotesService/CreateNote',
                request_serializer=notes__pb2.Note.SerializeToString,
                response_deserializer=notes__pb2.Note.FromString,
                )
        self.GetNote = channel.unary_unary(
                '/notes.NotesService/GetNote',
                request_serializer=notes__pb2.NoteId.SerializeToString,
                response_deserializer=notes__pb2.Note.FromString,
                )
        self.UpdateNote = channel.unary_unary(
                '/notes.NotesService/UpdateNote',
                request_serializer=notes__pb2.Note.SerializeToString,
                response_deserializer=notes__pb2.Note.FromString,
                )
        self.DeleteNote = channel.unary_unary(
                '/notes.NotesService/DeleteNote',
                request_serializer=notes__pb2.NoteId.SerializeToString,
                response_deserializer=notes__pb2.Note.FromString,
                )
        self.GetAllNotes = channel.unary_unary(
                '/notes.NotesService/GetAllNotes',
                request_serializer=notes__pb2.Empty.SerializeToString,
                response_deserializer=notes__pb2.NoteList.FromString,
                )


class NotesServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateNote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateNote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteNote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllNotes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateNote': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNote,
                    request_deserializer=notes__pb2.Note.FromString,
                    response_serializer=notes__pb2.Note.SerializeToString,
            ),
            'GetNote': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNote,
                    request_deserializer=notes__pb2.NoteId.FromString,
                    response_serializer=notes__pb2.Note.SerializeToString,
            ),
            'UpdateNote': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateNote,
                    request_deserializer=notes__pb2.Note.FromString,
                    response_serializer=notes__pb2.Note.SerializeToString,
            ),
            'DeleteNote': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteNote,
                    request_deserializer=notes__pb2.NoteId.FromString,
                    response_serializer=notes__pb2.Note.SerializeToString,
            ),
            'GetAllNotes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllNotes,
                    request_deserializer=notes__pb2.Empty.FromString,
                    response_serializer=notes__pb2.NoteList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'notes.NotesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NotesService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateNote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/notes.NotesService/CreateNote',
            notes__pb2.Note.SerializeToString,
            notes__pb2.Note.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/notes.NotesService/GetNote',
            notes__pb2.NoteId.SerializeToString,
            notes__pb2.Note.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateNote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/notes.NotesService/UpdateNote',
            notes__pb2.Note.SerializeToString,
            notes__pb2.Note.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteNote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/notes.NotesService/DeleteNote',
            notes__pb2.NoteId.SerializeToString,
            notes__pb2.Note.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllNotes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/notes.NotesService/GetAllNotes',
            notes__pb2.Empty.SerializeToString,
            notes__pb2.NoteList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
